# -*- coding: utf-8 -*-
"""
Implementation of FlipInts
Version 1.05
Date 2026-06-28

@author: Christopher Wolf, chris/at/Christopher-Wolf.de

The programme is under GNU General Public License v3, but not any later version.
https://www.gnu.org/licenses/gpl-3.0.html
The software is given "as it is", without the assumption that it can be used for a specific purpose.
In particular, it is not a reference implementation for FlipPolys as the source code
certainly contains vulnerabilities against side channel attacks.

Apart from that, it should help to illustrate the concepts of FlipInts.
"""

import math
import random
import datetime
import functools

from flipFields import isField,isElem,isPoly,isPolyRelaxed,poly2num,poly2str,plotState,log2int
from flipPolys import invMul as flipPolysInvMul


# =============================================================================
# # checks if D is of the form 2^(d+1)
# def is Ring(D):
#   if (D < 3): return False
#   while (D > 1): 
#     if (D % 2) == 1: return False
#     D //= 2
#   return True
# 
# # checks if a given input a is actually within the given odd ring D=2^(d+1)
# def is Elem(a,D):
#   if not(is Ring(D)): return False
#   if a <= 0: return False
#   if a >= D: return False
#   if (a % 2) != 1: return False
#   return True
# =============================================================================


def isVec(v,D):
  """
  Check if v is a vector in FlipInts generated by D.

  Parameters
  ----------
  v : list
    Vector over FlipInts generated by D.
  D : int
    Generate a FlipInts.

  Returns
  -------
  bool
    True iff all elements of v are in FlipInts of D.
  """
  for a in v: 
    if (isElem(a,D) != True): return False
  return True

 
def isLU_lower(L,D):
  """
  Check if a matrix is of the generalized lower matrix format.

  Parameters
  ----------
  L : list of lists
    Lower triangular matrix .
  D : int
    Generates the corresponding FlipInts with modulus D.

  Returns
  -------
  bool
    True iff L is a suitable generalized lower triangular matrix.
  """
  s = len(L)
  assert (s % 2) == 1, "s is even "+ str(s)
  for layer in range((s // 2) + 1):
    if layer == 0:
      assert L[0][0] == 1, "L[i,j] is not 1 L[i,j]="+str(L[0][0])+" i=0, j=0"
    else: 
      for i in range(layer*2-1, layer*2):
        for j in range(layer*2 + 1) :
          assert isElem(L[i][j],D), "L[i,j] is not an element for L[i,j]="+str(L[i][j])+" i="+str(i)+ " j="+str(j)
          if j == layer*2: assert L[i][j] == 1, "L[i,j] is not 1 but L[i,j]="+str(L[i][j])+" i="+str(i)+ " j="+str(j)
        for j in range(layer*2+1,s):
          assert L[i][j] == 0, "L[i,j] is none-zero for L[i,j]="+str(L[i][j])+" i="+str(i)+ " j="+str(j)
  return True        
  

# check if a matrix is of the generalized upper matrix format
def isLU_upper(U,D):
  """
  Check if a matrix is of the generalized upper matrix format.

  Parameters
  ----------
  U : list of lists
    Lower triangular matrix .
  D : int
    Generates the corresponding FlipInts with modulus D.

  Returns
  -------
  bool
    True iff U is a suitable generalized upper triangular matrix.
  """
  s = len(U)
  assert (s % 2) == 1, "s is even "+ str(s)
  for layer in range((s // 2)):
    for i in range(layer*2, layer*2+1):
      for j in range(layer*2,s):
        assert isElem(U[i][j],D), "U[i,j] is not an element for U[i,j]="+str(U[i][j])+" i="+str(i)+ " j="+str(j)
      for j in range(0,layer*2-1):
        assert U[i][j] == 0, "U[i,j] is none-zero for U[i,j]="+str(U[i][j])+" i="+str(i)+ " j="+str(j)
  assert isElem(U[s-1][s-1],D), "U[i,j] is not an element for U[i,j]="+str(U[i][j])+" i="+str(i)+ " j="+str(j)
  return True


##########################################################

def invMul(a,D):
  """
  Computes the multiplicative inverse using the Extended Euclidian algorithm.

  Parameters
  ----------
  a : int
    element of the corresponding flipInt
  D : int
    Modulus of the flipField.

  Returns
  -------
  t : int
    Integer t s/t a.t = 1 (mod D)
  """
  assert isElem(a,D), "is not an element a=%d for D=%d"%(a,D)
  t = 0; newT = 1; r = D; newR = a
  while newR != 0:
    q = r // newR
    tmp = newT; newT = t - q * newT; t = tmp  
    tmp = newR; newR = r - q*newR; r = tmp

  assert r <= 1, "r is too big: "+str(r)
  if t < 0: t = t + D
  assert isElem(t,D), "t is not an element: "+str(t)
  return t


def invHensel(a,D):
  """
  Computes the multiplicative inverse using Hensel's lifting.
  See for details (German):
  https://hwlang.de/zahlentheorie/hensel-lifting.htm  

  Parameters
  ----------
  a : int
    element of the corresponding flipInt
  D : int
    Modulus of the flipField.

  Returns
  -------
  t : int
    Integer t s/t a.t = 1 (mod D)
  """    
  def invRec(a, k):
    if k == 1: return 1
    D = 2**k
    a = a % D
    r = invRec(a, (k+1)//2)
    return (2-a*r) * r % D
      
   
  assert isElem(a,D), "is not an element a=%d for D=%d"%(a,D)
  k = log2int(D)
  assert 2**k == D, "k invalid for k=%d, D=%d"%(k,D)
  return invRec(a,k)
  

def applyMatVecOdd(M,x,D):
  """
  compute y = Mx for given M, x.
  All computations mod D and s an odd number.
  Input:
    M: (s x s) matrix
    x: (s x 1) vector
  Output
    y: (s x 1) vector

  Parameters
  ----------
  M : list
    Matrix in the form of list of lits of integers.
  x : list
    vector.
  D : int
    Generating number for a flipInt.

  Returns
  -------
  list
    Vector as a list of ints.
  """
  s = len(x)
  assert (s % 2) == 1, "s not odd: "+str(s)
  assert s == len(M), "mat has wrong size: "+str(len(M))

  # check the input
  for i in range(s):
    assert isElem(x[i],D), "x[i] is not an element for x[i]="+str(x[i])+" i="+str(i)

  for i in range(s):
    for j in range(s): 
      assert isElem(M[i][j],D), "M[i,j] is not an element for M[i,j]="+str(M[i][j])+" i="+str(i)+", j="+str(j) 
  
  # compute
  y = [0]*s  # prepare the result vector

  # apply x to M
  for i in range(s):
    curVec = M[i]
    assert s == len(curVec), "curVec has wrong size: "+str(len(curVec))
    accu = 0
    for j in range(s):
      accu += curVec[j] * x[j]
    y[i] = accu % D

  return y


# compute y = Mx for given M, x
# Input:
#   M: (s x s) matrix
#   x: (s x 1) vector
# Output
#   y: (s x 1) vector
# All computations mod D and s an odd number
def applyMatVecPlain(M,x,D):
  """
  compute y = Mx for given M, x.
  All computations mod D and s an odd number.

  Do not check if all numbers are elements of FlipInts.
  
  Input:
    M: (s x s) matrix
    x: (s x 1) vector
  Output
    y: (s x 1) vector

  Parameters
  ----------
  M : list
    Matrix in the form of list of lits of integers.
  x : list
    vector.
  D : int
    Generating number for a flipInt.

  Returns
  -------
  list
    Vector as a list of ints.
  """
  s = len(x)
  assert (s % 2) == 1, "s not odd: "+str(s)
  assert s == len(M), "mat has wrong size: "+str(len(M))

  # compute
  y = [0]*s  # prepare the result vector

  # apply x to M
  for i in range(s):
    curVec = M[i]
    assert s == len(curVec), "curVec has wrong size: "+str(len(curVec))
    accu = 0
    for j in range(s):
      accu += curVec[j] * x[j]
    y[i] = accu % D

  return y


# compute y = Mx for given M, y
# https://en.wikipedia.org/wiki/Iterative_method - iterative method
# https://en.wikipedia.org/wiki/Gauss%E2%80%93Seidel_method - GaussSeidel method
# Input:
#   M: (s x s) matrix
#   y: (s x 1) vector
# Output
#   x: (s x 1) vector
# All computations mod D and s an odd number
def solveMatVec(M,y,D):
  s = len(y)
  assert (s % 2) == 1, "s not odd: "+str(s)
  assert s == len(M), "mat has wrong size: "+str(len(M))

  # check the input
  for i in range(s):
    assert isElem(y[i],D), "y[i] is not an element for y[i]="+str(y[i])+" i="+str(i)
  for i in range(s):
    assert s == len(M[i]), "mat[i] has wrong size: "+str(len(M[i])+" for "+M[i])
    for j in range(s):      
      assert isElem(M[i][j],D), "M[i,j] is not an element for M[i,j]="+str(M[i][j])+" i="+str(i)+", j="+str(j) 

  # use Gaussian elimination on each column
  # stop if we get a zero on the column in the process---matrix not invertible in this case
  for fromRow in range(s):
    swapRow = -1
    if (M[fromRow][fromRow] % 2) == 0: 
      # swap rows
      for swapRow in range(fromRow+1,s):
        if (M[swapRow][fromRow] % 2) != 0: break
      assert swapRow >= 0, "Non-invertible matrix at fromRow="+str(fromRow)+" for M="+str(M)
      tmpRow = M[fromRow]; M[fromRow] = M[swapRow]; M[swapRow] = tmpRow
      tmpElem = y[fromRow]; y[fromRow] = y[swapRow]; y[swapRow] = tmpElem
    assert M[fromRow][fromRow] != 0, "Non-invertible matrix at fromRow="+str(fromRow)+" for M="+str(M)

    invFrom = invMul(M[fromRow][fromRow],D)
    # multiply the current row such that the pivot element is a one
    for curCol in range(fromRow,s):
      M[fromRow][curCol] = invFrom*M[fromRow][curCol] % D
    assert M[fromRow][fromRow] == 1, "Non-one pivot with "+str(M[fromRow][fromRow])  
    y[fromRow] = invFrom*y[fromRow] % D
    # subtract row by row to achieve zero in column fromRow
    for targetRow in range(fromRow+1,s):
      targetFac = M[targetRow][fromRow]
      for j in range(fromRow,s):
        M[targetRow][j] = (M[targetRow][j] - targetFac*M[fromRow][j]) % D
      # intermediate result
      assert M[targetRow][fromRow] == 0, "Non-Zero pivot at targetRow="+str(targetRow)+" fromRow="+str(fromRow)+" for "+str(M)
      y[targetRow] = (y[targetRow] - targetFac*y[fromRow]) % D
    
    # find gcd for each row and divide by it
    for curRow in range(fromRow+1,s):
      allElems = [y[curRow]] + M[curRow]
      allElems = list(filter(lambda x: x != 0, allElems))
      if allElems == []: curGCD = 1
      else: 
        curGCD = allElems[0]
        for i in range(1,len(allElems)): curGCD = math.gcd(curGCD,allElems[i])
      for curCol in range(fromRow+1,s): 
        assert (M[curRow][curCol] % curGCD) == 0, "Not dividible by "+str(curGCD)+" for "+str(M[curRow][curCol]) 
        M[curRow][curCol] //= curGCD
      assert (y[curRow] % curGCD) == 0, "Not dividible by "+str(curGCD)+" for "+str(y[curRow])
      y[curRow] //= curGCD
    
  # reconstruct x for Mx=y
  x = [0]*s  # prepare the result vector
  for fromRow in range(s-1,-1,-1):
    # apply y[fromRow] = Mx for x known so far
    accu = 0
    for curCol in range(fromRow+1,s):
      accu += M[fromRow][curCol]*x[curCol] % D
    assert M[fromRow][fromRow] == 1, "non-one element at "+fromRow+" with "+M[fromRow][fromRow]
    x[fromRow] = (y[fromRow] - accu) % D
#    assert isElem(x[fromRow],D), "non-element x="+str(x[fromRow])
  return x


# compute Ly = b for given L, b
# solve Ly = b 
# L is a generalized lower matrix over the integer carrier
# D is 2^(d+1) for the dimension d of the integer carrier
def solveLU_lower(L,b,D):
  
  # solve Ly = b for some intermediate solution y
  def solveRec_lower(L,b,s,layer,y,D):
    assert isLU_lower(L,D), "L is not generalized lower matrix for L="%str(L)
    assert layer*2 < s, "layer is too high for s for (layer,s)=("+str(layer)+","+str(s)+")"
    rL = layer*2+1  # starts with layer 0
    if rL >= s: return [y.copy()] # we have a solution, we are done
    
    # try all possible values from the input
    Y_out = [] 
    # apply different values of y to the current solution
    for yLower in range(1,D,2):
      ySolFirst = (b[rL] - (yLower*L[rL][rL] + sum(y[i]*L[rL][i] for i in range(rL)))) % D
      ySolSecond =  (b[rL+1] - (yLower*L[rL+1][rL] + sum(y[i]*L[rL+1][i] for i in range(rL)))) % D
      # verify if this is a solution for both equations layer*2, layer*2+1
      # check if we found a new, possible solution
      if ySolFirst == ySolSecond: 
        y[rL] = yLower; y[rL+1] = ySolFirst
        Y_out += solveRec_lower(L,b,s,layer+1,y,D)
    return Y_out
    
  # main method
  s = len(b)
  assert (s % 2) == 1, "s not odd: "+str(s)
  assert s == len(L), "mat L has wrong size: "+str(len(L))

  # check the input
  for i in range(s):
    assert isElem(b[i],D), "b[i] is not an element for b[i]="+str(b[i])+" i="+str(i)
  for i in range(s):
    assert s == len(L[i]), "L[i] has wrong size: "+str(len(L[i])+" for "+L[i])
    
  # check if L is in the right format  
  assert isLU_lower(L,D), "L is not lower form for L="+str(L)

  # solve Ly = b
  y = [1] * s
  # first layer in L
  y[0] = b[0]
  # recursively solve for all layers
  return solveRec_lower(L,b,s,0,y,D)

# compute Ux = y for given U,y
# solve Ux = y 
# U is a generalized upper matrix over the integer carrier
# D is 2^(d+1) for the dimension d of the integer carrier
def solveLU_upper(U,y,D):
  
  # solve Ux = y for some intermediate solution x
  def solveRec_upper(U,y,s,layer,x,D):
    if layer < 0: return [x.copy()] # we have a solution, we are done
    assert isLU_upper(U,D), "U is not generalized upper matrix for U="%str(U)
    assert layer*2 < s, "layer is too high for s for (layer,s)=("+str(layer)+","+str(s)+")"
    rU = layer*2  # starts with layer 0
    
    # try all possible values from the input
    X_out = [] 
    # apply different values of y to the current solution
    for xLower in range(1,D,2):
      x[rU+1] = xLower; 
      xSolFirst = (invMul(U[rU][rU],D)*(y[rU] - sum(U[rU][i]*x[i] for i in range(rU+1,s)))) % D
      xSolSecond =  (invMul(U[rU+1][rU],D)*(y[rU+1] - sum(U[rU+1][i]*x[i] for i in range(rU+1,s)))) % D
      # verify if this is a solution for both equations layer*2, layer*2+1
      # check if we found a new, possible solution
      if xSolFirst == xSolSecond: 
        x[rU+1] = xLower; x[rU] = xSolFirst
        X_out += solveRec_upper(U,y,s,layer-1,x,D)
    return X_out
    
  # main method
  s = len(y)
  assert (s % 2) == 1, "s not odd: "+str(s)
  assert s == len(U), "mat U has wrong size: "+str(len(U))

  # check the input
  for i in range(s):
    assert isElem(y[i],D), "y[i] is not an element for y[i]="+str(y[i])+" i="+str(i)
  for i in range(s):
    assert s == len(U[i]), "U[i] has wrong size: "+str(len(U[i])+" for "+U[i])
    
  # check if U is in the right format  
  assert isLU_upper(U,D), "U is not upper form for U="+str(U)

  # solve Ux = y
  x = [1] * s
  # lowest layer in U
  x[s-1] = (invMul(U[s-1][s-1], D) * y[s-1]) % D
  # recursively solve for all layers
  return solveRec_upper(U, y, s, (s // 2)-1, x, D) 
  
# solves LUx = b for some vector b and a lower and upper, generalized triangular matrix L, U, respectively
# return all possible solutions x as a list of vectors
def solveLU(L,U,b,D):
  s = len(b)
  assert (s % 2) == 1, "s not odd: "+str(s)
  assert s == len(L), "mat L has wrong size: "+str(len(U))

  # check the input
  for i in range(s):
    assert isElem(b[i],D), "b[i] is not an element for b[i]="+str(b[i])+" i="+str(i)
  for i in range(s):
    assert s == len(L[i]), "L[i] has wrong size: "+str(len(L[i])+" for "+L[i])
  for i in range(s):
    assert s == len(U[i]), "U[i] has wrong size: "+str(len(U[i])+" for "+U[i])

  # check if L is in the right format  
  assert isLU_lower(L,D), "L is not lower form for L="+str(L)   
  # check if U is in the right format  
  assert isLU_upper(U,D), "U is not upper form for U="+str(L)
  
  # solve the equation
  Y_out = solveLU_lower(L,b,D)
  X_out = []
  for y in Y_out:
    assert isVec(y,D), "Invalid solution "+str(y)
    X_out += solveLU_upper(U,y,D)
  return X_out  
  
#############################################################
# Polynomials

# returns A(X). B(X)for two polynomials
def mulPoly(A,B,D):
  assert isPoly(A,D), "A not valid with "+str(A)
  assert isPoly(B,D), "B not valid with "+str(B)
  R = {}  # prepare the result
  # multiply AB
  for a in A.keys():
    for b in B.keys():
      new = a+b
      if not(new in R): R[new] = 0
      R[new] += A[a]*B[b]
  # reduce R    
  for k in R.keys():
    R[k] = R[k] % D    
  return R
  
# for some given polynomial A and target degree deg,
# itentify the coefficients so we can find some polynomial B s/t A.B is a polynomial
# over the odd ring mod D
def mulPolyFindBCoeffs(A,deg,D):
  assert isPoly(A, D), "Error mulPolyFindRndB - no odd poly for "+str(A)
  allCoeffs = {}
  # perform multiplication on the level of X
  for a in A.keys():
    for b in range(deg+1):
      new = a+b
      if not(new in allCoeffs): allCoeffs[new] = 0
      allCoeffs[new] += 1
  # identify degrees that are even
  zeroCoeffs = {}
  for ac in allCoeffs:
    if (allCoeffs[ac]) % 2 == 0: zeroCoeffs[ac] = allCoeffs[ac]
  # similar coeffs
  similarCoeffs = {}
  for a in A.keys():
    for b in range(deg+1):
      if a+b in zeroCoeffs: 
        if not(a+b) in similarCoeffs: similarCoeffs[a+b] = []
        similarCoeffs[a+b].append([a,b])
  return similarCoeffs      
      

#############################################################
# rndElems

# returns a random vector of length s mod D
def rndVecOdd(s,D): 
  assert (s % 2) == 1, "even s with "+str(s)  
  fromList = range(1,D,2)
  resVec = s*[1]
  for i in range(len(resVec)):
    resVec[i] = random.choice(fromList)  
  return resVec 

# returns a random matrix of size (s x s) mod D
def rndMatOdd(s,D):
  assert (s % 2) == 1, "even s with "+str(s)  
  M = [1]*s
  for i in range(s):
    M[i] = rndVecOdd(s,D)   
  return M  

# generate a lower triangular matrix 
def rndLU_lower(s,D):
  # generate a random lower matrix and modify it layer by layer
  L = rndMatOdd(s,D)
  # set first row
  L[0][0] = 1
  for i in range(1,s): L[0][i] = 0
  # set all other rows
  for layer in range(1,s//2+1):
    layRow = layer*2-1
    L[layRow][layRow+1] = 1
    L[layRow+1][layRow+1] = 1
    for i in range(layRow+2,s):
      L[layRow][i] = 0
      L[layRow+1][i] = 0
  # test if we created the correct matrix
  assert isLU_lower(L,D)     
  return L

# generate an upper triangular matrix 
def rndLU_upper(s,D):
  # generate a random upper matrix and modify it layer by layer
  U = rndMatOdd(s,D)
  for layer in range((s // 2)):
    for i in range(layer*2, layer*2+1):
      for j in range(0,layer*2-1):
        U[i][j] = 0
  assert isLU_upper(U,D)      
  return U

# generate random matrices and try to solve 
# Mx = y 
# for given M,y. Report algorithm failures.
# Write the result to a res-file
# used to dermine if solveMatVec can be used to solve matrix/vector equations over odd rings
def rndMatTest():  
  fileOut = 0
  totalCnt = 0 # total number of repetitions
  menuS = [3,5,7,9,11,13,17,25,37, 41, 43,45,47,57,69,81,93,101,113 ]
  menuD = [16, 128, 256, 512, 65536]
  #menuS = [3,5,7 ]
  #menuD = [16, 128]

  targetVars = ["AnumRep", "Bsucc", "CfailAlg","DfailErg"]
  # generate tags
  dictCases = {}
  dictVars = {}
  for s in menuS:
    for D in menuD:
      tag = "s%3d_D%5d_"%(s,D)
      dictCases[tag] = [s,D]
      allTags = list(tag+x for x in targetVars)
      for v in allTags: dictVars[v] = 0
      
  # infinity loop
  while (True):    
    # give current date and time
    now = datetime.datetime.now()
    print(now.strftime("%Y-%m-%d %H:%M:%S"))
    
    # iterate over all possible cases
    for curCase in dictCases:
      s = dictCases[curCase][0]  
      D = dictCases[curCase][1]
    
      repCnt = random.randint(63, 127)
      totalCnt += repCnt
  
      # apply the full menu for testing
      for tstNum in range(repCnt):
        b = rndVecOdd(s,D); M = rndMatOdd(s,D)
        # check if invertible
        try:
          y = solveMatVec(M,b,D)    
          # check if y is a valid solution
          falseSol = False
          for i in range(s):
            if not(isElem(y[i],D)): falseSol = True; break   
          # check if the solution solves the original equation
          if not(falseSol): 
            x = applyMatVecPlain(M,y,D)
            if x != b: falseSol = True
          if falseSol: dictVars[curCase+"DfailErg"] += 1;
          else: dictVars[curCase+"Bsucc"] += 1
        except AssertionError:  
          dictVars[curCase+"CfailAlg"] += 1
        dictVars[curCase+"AnumRep"] += 1 
    # write the current result to a file
    fileOut = (fileOut +1) % 7
    fileName = "outStat/out" + str(fileOut) + ".txt"
    with open(fileName, "w") as f:
      # write the whole content of dictCases
      f.write("Date/Time"+now.strftime("%Y-%m-%d %H:%M:%S"))
      f.write("\ntotal number of repetitions: %d\n\n"%totalCnt)
      sOld = -1
      for curCase in sorted(dictCases.keys()):
        s = dictCases[curCase][0]  
        D = dictCases[curCase][1]
        if (sOld != s): f.write("\\\\ \n\\hline \n   "); f.write("%d & "%s)
        else: f.write("\\\\\n     & ")
        sOld = s
      
        f.write("   %d  "%D)
        # #rep
        rep = dictVars[curCase+"AnumRep"]  
        succ = dictVars[curCase+"Bsucc"]; propSucc = succ / rep
        failAlg = dictVars[curCase+"CfailAlg"]; propAlg = failAlg / rep
        failErg = dictVars[curCase+"DfailErg"]; propErg = failErg / rep
      
        f.write("& %d "%(rep))
        f.write("& %d & %7.5f "%(succ, propSucc))
        f.write("& %d & %7.5f "%(failAlg, propAlg))
        f.write("& %d & %7.5f "%(failErg, propErg))
      
      
      # write the whole dictionary
      f.write("\n\n\n")
      f.write(str(dictCases))
      f.write("\n\n\n")
      f.write(str(dictVars))
      f.write("\nEnde\n")
      
      f.close()
    # end infinity loop    
    
# generate random LU-decompositions and try to solve 
# LUx = b 
# for given L,U,b. Report algorithm failures.
# Write the result to a res-file
# used to dermine if solveMatVec can be used to solve matrix/vector equations over odd rings
def rndTestLU():  
  fileOut = 0
  totalCnt = 0 # total number of repetitions
  menuS = [3,5,7,9,11,13,17,25,37, 41, 43,45,47,57,69,81,93,101,113 ]
  menuD = [16, 128, 256, 512, 65536]
  #menuS = [3,5,7 ]
  #menuD = [16, 128]

  now = datetime.datetime.now()
  startTime = now.strftime("%Y-%m-%d %H:%M:%S")

  targetVars = ["AnumRep", "Bsucc", "BnumSols", "CfailSol","DfailAlg"]
  # generate tags
  dictCases = {}
  dictVars = {}
  for s in menuS:
    for D in menuD:
      tag = "s%3d_D%5d_"%(s,D)
      dictCases[tag] = [s,D]
      allTags = list(tag+x for x in targetVars)
      for v in allTags: dictVars[v] = 0
      
  # infinity loop
  while (True):    
    print("Start Time: "+startTime)
    # give current date and time
    now = datetime.datetime.now()
    print(now.strftime("%Y-%m-%d %H:%M:%S"))
    
    # iterate over all possible cases
    for curCase in dictCases:
      s = dictCases[curCase][0]  
      D = dictCases[curCase][1]
    
      repCnt = random.randint(63, 127)
      totalCnt += repCnt
  
      # apply the full menu for testing
      for tstNum in range(repCnt):
        b = rndVecOdd(s,D)
        L = rndLU_lower(s,D); U = rndLU_upper(s,D)
        dictVars[curCase+"AnumRep"] += 1 
        # check if invertible
        try:
          X_out = solveLU(L,U,b,D)  
          if len(X_out) >= 1: dictVars[curCase+"Bsucc"] += 1
          for x in X_out:
            # check if y is a valid solution
            falseSol = False
            for i in range(s):
              if not(isElem(x[i],D)): falseSol = True; break   
            # check if the solution solves the original equation
            trueSol = False
            if not(falseSol): 
              y = applyMatVecPlain(U,x,D)
              bDash = applyMatVecPlain(L,y,D)
              if bDash == b: trueSol = True
            if trueSol: dictVars[curCase+"BnumSols"] += 1
            else: dictVars[curCase+"CfailSol"] += 1;
        except AssertionError:  
          dictVars[curCase+"DfailAlg"] += 1
    # write the current result to a file
    fileOut = (fileOut +1) % 7
    fileName = "outStat/out" + str(fileOut) + ".txt"
    with open(fileName, "w") as f:
      # write the whole content of dictCases
      f.write("Start Date/Time: "+startTime)
      f.write("Date/Time"+now.strftime("%Y-%m-%d %H:%M:%S"))
      f.write("\ntotal number of repetitions: %d\n\n"%totalCnt)
      sOld = -1
      f.write("# "+str(targetVars))
      for curCase in sorted(dictCases.keys()):
        s = dictCases[curCase][0]  
        D = dictCases[curCase][1]
        if (sOld != s): f.write("\\\\ \n\\hline \n   "); f.write("%d & "%s)
        else: f.write("\\\\\n     & ")
        sOld = s
      
        f.write("   %d  "%D)
        # #rep
        rep = dictVars[curCase+"AnumRep"]  
        succ = dictVars[curCase+"Bsucc"]; propSucc = succ / rep
        numSols = dictVars[curCase+"BnumSols"]; propSols = numSols / rep
        failSol = dictVars[curCase+"CfailSol"]; propFailSol = failSol / rep
        failAlg = dictVars[curCase+"DfailAlg"]; propAlg = failAlg / rep
      
        f.write("& %d "%(rep))
        f.write("& %d & %7.5f "%(succ, propSucc))
        f.write("& %d & %7.5f "%(numSols, propSols))        
        f.write("& %d & %7.5f "%(failSol, propFailSol))
        f.write("& %d & %7.5f "%(failAlg, propAlg))
      
      
      # write the whole dictionary
      f.write("\n\n\n")
      f.write(str(dictCases))
      f.write("\n\n\n")
      f.write(str(dictVars))
      f.write("\nEnd\n")
      
      f.close()
    # end infinity loop     
  
    
def checkNearOdd():
  """
  Plots how high the probability for near-odd-pairs is for a given D by randomly choosing two elements from a FlipInt

  Returns
  -------
  None.

  """   
  D = 65536
  resDict = {i:0 for i in range(1000)}
  for i in range(1000):
    fromList = range(1,D,2)
    a = random.choice(fromList); b = random.choice(fromList)    
    diff = (a-b) % D
    # see how many 2 we cam extract
    res = 0
    while ((diff % 2) == 0) and (diff != 0):
      res += 1
      diff //= 2
    resDict[res] += 1
  for i in [a for a in resDict.keys()]:
    if resDict[i] == 0: del resDict[i]
  print("res: {}".format(resDict))  


#############################################################
# symbolic computation
def symIsPoly(p,v,D,relaxed=True):
  """
  Checks if a polynomial string is well-formed, i.e.
  - each term starts with a number
  - all other factors in this term are a variable from v
  - the term closes with "*"
  
  Parameters
  ----------
  p : str
    Polynomial.
  v : set of str
    variables.
  D : int
    Modulus of the flipField.
  relaxed : bool
    Skip check if all factors are elements of the flipInts  

  Returns
  -------
  bool
    True iff p is well-formed regarding v, D
  """
  assert isField(D), "no field for D=%d"%D
  
  # check if the input is valid
  if p[-1] != "*": return False
    
  # split by terms
  terms = p.split("+")  
  for t in terms:
    facs = t.split("*")
    if facs[-1] != "": return False
    if not(facs[0].isdigit()): return False
    if not(relaxed) and not(isElem(int(facs[0]),D)): return False
    for f in facs[1:-1]:
      if not(f in v): return False
  return True 


def symPolyIsOdd(p,D):
  """
  Returns if the sum of the factors of the polynomial are odd.
  Assuming all input variables are odd, the output will be odd, too.

  Parameters
  ----------
  p : str
    Polynomial as a string.
  D : int
    Generator of the flipInts.

  Returns
  -------
  bool
    True iff the sum of the factors is odd.
  """
  assert isField(D), "no field for D=%d"%D
  
  # check if the input is valid
  if p[-1] != "*": return False
    
  # split by terms, get the factors
  terms = p.split("+") 
  sumFac = 0
  for t in terms:
    facs = t.split("*")
    if facs[-1] != "": return False
    if not(facs[0].isdigit()): return False
    sumFac += int(facs[0])
  return (sumFac % 2) == 1


def symIsLinear(p,v,D):
  """
  Verifies if p is a valid polynomial and also of degree 1.

  Parameters
  ----------
  p : str
    Polynomial.
  v : set of str
    variables.
  D : int
    Modulus of the flipField.

  Returns
  -------
  bool
    True iff the input polynomial is linear.
  """
  assert symIsPoly(p,v,D), "Not a polynomial with "+p
  return functools.reduce(lambda a,b: a and b, [ s.count("*") == 2 for s in p.split("+") ] )


def symAllVars(inEq,D):
  """
  Returns all variables for a given equation.

  Parameters
  ----------
  inEq : str
    Equation.

  Returns
  -------
  set
    set of all variables in this equation.
  """
  outSet = set()
  if inEq == "": return outSet
  for t in inEq.split("+"):
    for f in t.split("*"):
      if (len(f) > 0) and not(f.isdigit()): outSet.add(f)
  assert symIsPoly(inEq,outSet,D), "Wrong equation for "+inEq
  return outSet    


def symSetEqs(eqs,v,var2val,D):
  """
  For a given list of equations, replace one variable by an integer value.

  Parameters
  ----------
  eqs : list
    Equations as list of strings.
  v : set
    set of variables (as strings).
  var2val : dict
    variable to a definite value.
  D : int
    fieldInt.

  Returns
  -------
  list
    list of strings. Equations after replacing a variable.
  """
  # check if each equation is well-formed
  for eq in eqs:
    assert symIsPoly(eq,v,D), "Problem Eq  " + eq 
  assert (len(var2val.keys())) == 1, "Too many variables with " +str(var2val) 
  curKey = list(var2val.keys())[0]
  curVar = var2val[curKey]
  assert str(curVar).isdigit(), "Non-digit value for "+str(var2val)+" and !%s!"%(curVar)
  targetVar = "*" + str(curKey) + "*"
  # if applicable, replace each variable in var2val by its value
  for i in range(len(eqs)):
    pos = eqs[i].find(targetVar)
    if pos < 0: continue
    # split the equation
    terms = eqs[i].split("+")
    outList = []
    for t in terms:
      pos = t.find(targetVar)
      if pos < 0: 
        outList.append(t)
        continue
      t = t.replace(targetVar,"*")
      # only get the constant term
      monConst = t.split("*",1)
      assert monConst[0].isdigit()
      fac = int(monConst[0]) * var2val[curKey] % D
      # make sure we have a non-zero term
      if fac == 0: continue
      outStr = str(fac) + "*"
      outStr += monConst[1]
      outList.append(outStr)
    eqs[i] = "+".join(outList) 
  # check the output
  for eq in eqs:
    assert symIsPoly(eq,v,D), "Problem Eq 2: " + eq   
  return eqs    


def symSetEqsPoly(eqs,v,var2poly,D):
  """
  Replaces a given variable by a polynomial. Multiplies out and collects terms in the process.
  The result is a valid polynomial in the given set of variables.

  Parameters
  ----------
  eqs : list
    List of str, each of them is a valid polynomial.
  v : set
    Set of variables that form the polynomial.
  var2poly : dict
    New polynomial for a variable. Only one variable is allowed, i.e. the dictionary only has one key.
  D : int
    Generating integer for the corresponding flipInts.

  Returns
  -------
  TYPE
    DESCRIPTION.
  """
  assert isField(D), "Wrong flipInts with "+str(D)
  for eq in eqs:
    assert symIsPoly(eq,v,D), "Problem Eq  " + eq 
  assert (len(var2poly.keys())) == 1, "Too many variables with " +str(var2poly) 
  curKey = list(var2poly.keys())[0]
  curVar = var2poly[curKey]
  
  assert (var2poly[curKey] == "") or (symIsPoly(var2poly[curKey],v,D)), "Non polynomial value for "+str(var2poly)+" and !%s!"%(curVar)
  targetVar = "*" + str(curKey) + "*"  
  newTerms = var2poly[curKey].split("+")
  if var2poly[curKey] == "": newTerms = ["0*"]
  for i in range(len(eqs)):
    pos = eqs[i].find(targetVar)
    if pos < 0: continue
    # split the equation
    terms = eqs[i].split("+")
    outList = []
    for t in terms:
      pos = t.find(targetVar)
      if pos < 0: 
        outList.append(t)
        continue
      for newTerm in newTerms:
        newT = t.replace(targetVar,"*"+newTerm)
        newT = symSortTerms(newT, v, D)
        if newT != "0*": outList.append(newT)
    newEq = "+".join(outList)  
    eqs[i] = symAddUp(newEq,D)
  while "" in eqs: eqs.remove("")
  # check the output
  for eq in eqs:
    assert symIsPoly(eq,v,D,relaxed=True), "Problem Eq 2: " + eq   
  return eqs    


def symSortTerms(inEq,v,D):
  """
  For a given polynomial, sorts all terms and also multiplies out factors.

  Parameters
  ----------
  inEq : str
    Input polynomial.
  v : set
    Set of all variables in the input polynomial.
  D : int
    Number generating the corresponding flipInts.

  Returns
  -------
  str
    Sorted and multiplied polynomial.
  """
  assert isField(D), "Invalid flipInts with "+str(D)
  outEq = ""
  for t in inEq.split("+"):
    allVars = t.split("*")
    allVars.remove("")
    f = 1
    for a in allVars:
      if not(a.isdigit()): continue
      f *= int(a)
    f %= D  
    allVars = filter(lambda a: not(a.isdigit()),allVars)
    allVars = sorted(allVars)  
    if outEq != "": outEq += "+"
    outEq += str(f)+"*"+"*".join(allVars)
    if len(allVars) > 0: outEq += "*"
  return outEq  


def symPolyMult(leftPrefix, leftCnt, rightPrefix, rightCnt, D):
  """
  Multiply two polynomials in a given number of variables each.

  Parameters
  ----------
  leftPrefix : str
    Variable of the left factor
  leftCnt : int
    Maximal degree of the left polynomial.
  rightPrefix : str
    Variable of the right factor.
  rightCnt : int
    Maximal degree of the right polynomial.
  D : int
    Generating number for the flipInt  

  Returns
  -------
  list
    List of strings, result of this multiplication.
  """
  outList = []
  for k in range(leftCnt+rightCnt-1):
    outList.append("")
  for i in range(leftCnt):
    for j in range(rightCnt):
      if outList[i+j] != "": outList[i+j] += "+"
      outList[i+j] += "1*" + leftPrefix + str(i) + "*" + rightPrefix + str(j) + "*"
  v = set([leftPrefix + str(i) for i in range(leftCnt)] + [rightPrefix + str(j) for j in range(rightCnt)])    
  for curEq in outList:    
    assert symIsPoly(curEq,v,D), "Problem Eq  " + curEq 
  return outList


def symMulPolyPoly(left, right, D):
  """
  Symbolic multiplication of two polynomials.

  Parameters
  ----------
  left : str
    Polynomial.
  right : str
    Polynomial.
  D : int
    generating number for the flipInt.

  Returns
  -------
  str
    (left * right) % D. All terms are alphabetically sorted and added up.
  """
  assert isField(D), "Invalid flipInts with "+str(D)
  v = symAllVars(left,D).union(symAllVars(right,D))
  assert symIsPoly(left,v,D), "Problem left " + left 
  assert symIsPoly(right,v,D), "Problem right " + right
  leftTerms = left.split("+")
  rightTerms= right.split("+")
  # multiply term by term
  resTerms = ""
  for l in leftTerms:
    facLeft,l = l.split("*",1)
    for r in rightTerms:
      facRight,r = r.split("*",1)
      fac = (int(facLeft) * int(facRight)) % D
      tmpTerm = str(fac) + "*" + l + r
      # collect and rewrite
      resTerms = resTerms + "+" + tmpTerm if resTerms != "" else tmpTerm
  resTerms = symSortTerms(resTerms,v,D)
  resTerms = symAddUp(resTerms,D)
  return resTerms    


def symSubtractTerm(eqStr, subStr, D):
  """
  Subtract subStr from the current equation.

  Parameters
  ----------
  eqStr : str
    Polynomial for the current equation.
  subStr : str
    Term to be subtracted.
  D : int
    Current FlipInts.

  Returns
  -------
  str
    New polynomial.
  """
  subSplit = subStr.split('*',1)
  subFac = int(subSplit[0]); subTerm = subSplit[1]
  allTerms = eqStr.split('+')
  outEq = ""
  isIn = False
  termList = []
  for curTerm in allTerms:
    if curTerm == "": continue
    fullSplit = curTerm.split('*',1)
    fac = int(fullSplit[0]); term = fullSplit[1]
    if subTerm == term:
      isIn = True
      newFac = (D + fac - subFac) % D
      if newFac != 0: termList.append(str(newFac) + "*" + subTerm)
    else: termList.append(curTerm)
  if isIn == False: 
    newFac = (D - subFac) % D; 
    if outEq != "": outEq += "+"
    termList.append(str(newFac) + "*" + subTerm)
  outEq = "+".join(termList)  
  return outEq
  

def symAddUp(inEq,D):
  """
  Adds up all terms that share the same variables. Assumes all terms are well-ordered.

  Parameters
  ----------
  inEq : str
    input equation.
  D : int
    Generating number for the flipInts.

  Returns
  -------
  set
    Output equation.
  """
  v = symAllVars(inEq, D)
  if inEq == "": return ""
  assert symIsPoly(inEq,v,D), "Problem In Eq " + inEq 
  outDict = {}
  for t in inEq.split("+"):
    fac,allVars = t.split("*",1)
    if not(allVars in outDict): outDict[allVars] = 0
    outDict[allVars] = (outDict[allVars] + int(fac)) % D
  # delete zero equations
  for curVar in list(outDict.keys()):
    if outDict[curVar] == 0: del outDict[curVar]
  # generate output
  outEq = "+".join([ str(outDict[v])+"*"+v for v in sorted(outDict.keys()) ])
  # delete 0 terms
  assert symIsPoly(inEq,v,D), "Problem Out Eq " + outEq 
  return outEq


def symMultFacPoly(f,p,v,D):
  """
  Multiplies a given polynomial p by an integer factor f. 

  Parameters
  ----------
  f : int
    Factor.
  p : str
    Polynomial.
  v : set
    Set of all variables.
  D : int
    Modul generating the flipInts.

  Returns
  -------
  str
    Polynomial.
  """
  assert symIsPoly(p,v,D), "Problem Eq " + p
  assert isElem(f, D)
  outStr = ""
  for t in p.split("+"):
    fac,rest = t.split("*",1)
    fac = (int(fac)*f) % D
    if outStr != "": outStr += "+"
    outStr += str(fac) + "*" + rest
  return outStr  
  

def symRewriteEqsLin(leftPrefix, leftCnt, rightPrefix, rightCnt, rightSet, D):
  """
  Removes all closed equations, i.e. equations that have coefficients that add up to an even number.
  All remaining equations are active, i.e. their coefficients add up to an odd number. These produce odd output.

  Parameters
  ----------
  leftPrefix : str
    Prefix for the variables in the polynomial in the left term.
  leftCnt : int
    Number of variables for the left term in the polynomial.
  rightPrefix : str
    Prefix for the variables in the polynomial in the right term.
  rightCnt : int
    Number of variables for the right term in the polynomial.
  rightSet : dict
    Dictionary for the variable in the right factor that are set in the result.
  D : int
    Generating number for the flipInts.

  Returns
  -------
  eqs : list
    Equations in form of polynomials. The output variable is implicit.
  fullReplace : dict
    Variables that have been replaced by polynomials.
  """
  assert isinstance(rightSet,dict), "No dict for "+str(rightSet)
  # generate the system of equations by multiplying left and right variables
  eqs = symPolyMult(leftPrefix, leftCnt, rightPrefix, rightCnt, D)
  # assign random values to the rhs
  allVars = set([ leftPrefix + str(i) for i in range(leftCnt) ] + [ rightPrefix + str(j) for j in range(rightCnt)])
  fullReplace = {}
  for curVar in [ rightPrefix + str(j) for j in range(rightCnt)]:
    assert curVar in rightSet, "Variable does not exist in rightSet for "+curVar
    eqs = symSetEqs(eqs, allVars, {curVar: rightSet[curVar]} , D)
  
  # simplify the system, eliminate closed equations
  done = False
  while (not done):
    done = True
    # check if some polynomial has only one variable - this means the variable is zero
    # check if we have closed equations
    while len(eqs) != 0:
      # check if all equations are linear
      for j in range(len(eqs)): 
        assert symIsLinear(eqs[j],allVars,D), "Non-linear equation for "+eqs[j]
      # find a closed equation with minimal number of terms  
      i = -1; foundEq = -1; foundCnt = 10**100; foundLen = 10**100
      while True:
        i += 1    
        if i >= len(eqs): break
        if symPolyIsOdd(eqs[i-1],D): continue # active equation
        
        eqLen = len(eqs[i])
        cnt = eqs[i-1].count("+")
        if (cnt < foundCnt) or ((cnt == foundCnt) and (eqLen < foundLen)): foundCnt = cnt; foundEq = i-1; foundLen = eqLen  
      if foundEq == -1: break  # no closed equation      
      # remove one variable, make sure leading term is 1
      if eqs[foundEq].count("+") >= 1: t,r = eqs[foundEq].split("+",1)
      else: t = eqs[foundEq]; r = ""
      
      f,v = t.split("*",1)
      assert f.isdigit(), "Wrong number with "+f
      
      f = int(f); 
      if (f % 2) == 1:
        f = (D -f) % D; f = invMul(f, D)
      else:
        # we have an even factor here---split into two odd factors
        r += ("" if r=="" else "+") + (str((f-1) % D))+"*"+v
        f = 1
      repVar = v.replace("*","")
      if r != "": r = symMultFacPoly(f, r, allVars, D)
      fullReplace[repVar] = r
      # remove var/Eqs
      del eqs[foundEq]
      # set the variable accordingly
      eqs = symSetEqsPoly(eqs,allVars,{repVar: fullReplace[repVar]},D)
              
      done = False
    return eqs,fullReplace

#############################################################
# Printing
def printExamples():
  """
  Print concrete examples for matrix-vector equations

  Returns
  -------
  None.
  """
  # simple (3 x 3)-solving
  print("first example")
  M = [[3,1,1],[3,3,7],[5,5,5]]
  y = [1,5,7]
  x = solveMatVec(M,y,16)
  yDash = applyMatVecPlain(M,x,16)
  if (y != yDash): print("Error solveMathVec.1 with "+str(y))
  
  print("end examples\n\n")      
  
  
def SboxBijective():
  """
  Print concrete output for S-boxes
  Returns
  -------
  None.
  """
  filePrefix = "sBox"; saveState = {}; outStr = ""
  plotState(filePrefix,saveState,outStr)
  #for D in [256*2]:
  for D in [16*2,256*2,1024*2,4096*2,65536*2]:
    assert isField(D)
    Sbox = {}
    for i in range(1,D,2):
      Sbox[i] = (i**127) % D
      #Sbox[i] = flipPolysInvMul(i,D)
    outSet = set(Sbox.values())  
    if len(outSet) < D // 2: print("not bijective for {} with {}".format(D,len(outSet)))   
    else: outStr += "is bijective for {} with {}\n".format(D,len(outSet))
    
    if D == 2*16:
      outStr += "D=32\n"
      for i in range(1,D,2):
        outStr += "{} & {} \\\\ \n".format(i // 2,Sbox[i] // 2)
    
    if D == 2*256:
      outStr += "D=512\n"
      outStr += "% x\n"
      outStr += "  "
      for x in range(16):
        print("x={}".format(x))
        outStr += " & {:02x}".format(x)
      outStr += "\\\\ \n"  
      for y in range(16):
        print("y={}".format(y))
        outStr += "{:02x}".format(y*16)
        for x in range(16):
            i = (x + 16*y)*2+1
            print("i={}".format(i))
            outStr += " & {:02x}".format(Sbox[i]//2)
        outStr += "\\\\ \n"      
          
    saveState = plotState(filePrefix,saveState,outStr)  
    outStr += "\n\n"


def printSym():
  for j in range(10):
    sSet = dict()
    for i in range(64):
      sSet["s"+str(i)] = random.choice([1,3,5])
    outTup = symRewriteEqsLin("a", 35 , "s", 35, sSet, 512)  
    print("{}. #eqs, #replace: {} {}".format(j,len(outTup[0]),len(outTup[1])))
   

#############################################################
# Unit testing
def testAll():
  print("Start Testing")

  if invMul(1,8) != 1: print('Error invMul.1')
  if invMul(3,8) != 3: print('Error invMul.2')
  if invMul(5,8) != 5: print('Error invMul.3')
  if (invMul(11,256) * 11) % 256 != 1: print("Error invMul.4")
  if (invMul(13,256) * 13) % 256 != 1: print("Error invMul.5")
  if (invMul(255,256) * 255) % 256 != 1: print("Error invMul.6")
  if (invMul(11,512) * 11) % 512 != 1: print("Error invMul.7")
  if (invMul(13,512) * 13) % 512 != 1: print("Error invMul.8")
  if (invMul(255,512) * 255) % 512 != 1: print("Error invMul.9")

  D = 1024; a = 3
  i = invHensel(a,D); i2 = invMul(a,D)
  if i != i2: print("Error invHensel.1 %d %d"%(i,i2))
  D = 1024; a = 7
  i = invHensel(a,D); i2 = invMul(a,D)
  if i != i2: print("Error invHensel.2 %d %d"%(i,i2))
  D = 2048; a = 1023
  i = invHensel(a,D); i2 = invMul(a,D)
  if i != i2: print("Error invHensel.3 %d %d"%(i,i2))

  # new test---applying over the integers
  M = [[1,1,1],[1,1,1],[1,1,1]]
  x = [1,1,1]
  y = applyMatVecPlain(M,x,16)
  if (y != [3,3,3]): print("Error applyMathVecPlain.1 with "+str(y))
  M = [[1,1,1],[1,3,1],[1,1,3]]
  x = [1,3,5]
  y = applyMatVecPlain(M,x,16)
  if (y != [9,15,3]): print("Error applyMathVecPlain.2 with "+str(y))
  # new test
  M = [[3,5,7],[1,5,7],[7,5,1]]
  x = [1,3,5]
  y = applyMatVecPlain(M,x,16)
  if (y != [5,3,11]): print("Error applyMathVecPlain.3 with "+str(y))
  # new test
  M = [[3,1,1,1,1],[1,5,1,1,1],[1,1,7,1,1],[1,1,1,9,1],[1,1,1,1,13]]
  x = [1,3,5,7,11]
  y = applyMatVecPlain(M,x,64)
  if (y != [29, 39, 57, 19, 31]): print("Error applyMathVecPlain.4 with "+str(y))

  # new test---applying
  M = [[1,1,1],[1,1,1],[1,1,1]]
  x = [1,1,1]
  y = applyMatVecOdd(M,x,16)
  if (y != [3,3,3]): print("Error applyMathVecOdd.1 with "+str(y))
  M = [[1,1,1],[1,3,1],[1,1,3]]
  x = [1,3,5]
  y = applyMatVecOdd(M,x,16)
  if (y != [9,15,3]): print("Error applyMathVecOdd.2 with "+str(y))
  # new test
  M = [[3,5,7],[1,5,7],[7,5,1]]
  x = [1,3,5]
  y = applyMatVecOdd(M,x,16)
  if (y != [5,3,11]): print("Error applyMathVecOdd.3 with "+str(y))
  # new test
  M = [[3,1,1,1,1],[1,5,1,1,1],[1,1,7,1,1],[1,1,1,9,1],[1,1,1,1,13]]
  x = [1,3,5,7,11]
  y = applyMatVecOdd(M,x,64)
  if (y != [29, 39, 57, 19, 31]): print("Error applyMathVecOdd.4 with "+str(y))

  # new test---solving
  M = [[3,1,1],[1,3,1],[1,1,3]]
  y = [1,5,7]
  x = solveMatVec(M,y,16)
  yDash = applyMatVecPlain(M,x,16)
  if (y != yDash): print("Error solveMathVec.1 with "+str(y))
  # new test
  M = [[3,5,7],[1,5,7],[7,5,1]]
  y = [5,3,11]
  x = solveMatVec(M,y,16)
  yDash = applyMatVecPlain(M,x,16)
  if (y != yDash): print("Error solveMathVec.2 with "+str(y))
  # new test
  M = [[3,1,1,1,1],[1,3,1,1,1],[1,1,3,1,1],[1,1,1,3,1],[1,1,1,1,3]]
  y = [1, 3, 5, 7, 9]
  x = solveMatVec(M,y,16)
  yDash = applyMatVecPlain(M,x,16)
  if (y != yDash): print("Error solveMathVec.3 with "+str(y))
  
  # new test---LU Decomposition, lower
  L = [[1,0,0,0,0],
       [1,3,1,0,0],
       [1,3,1,0,0],
       [1,3,1,7,1],
       [1,3,7,1,1]]
  y = [1,3,5,7,9]
  b = applyMatVecPlain(L,y,16) 
  yDash = solveLU_lower(L,b, 16)
  for curY in yDash:
    assert isVec(curY,16)
    if b != applyMatVecPlain(L,curY,16):
      print("Error solveLU_lower.1 with %d and %d"%(curY, b))
  # new test---LU Decomposition, lower
  L = [[1,0,0,0,0],
       [1,3,1,0,0],
       [1,3,1,0,0],
       [1,3,1,7,1],
       [1,3,7,1,1]]
  y = [1,5,5,3,9]
  b = applyMatVecPlain(L,y,16) 
  yDash = solveLU_lower(L,b, 16)
  for curY in yDash:
    assert isVec(curY,16)
    if b != applyMatVecPlain(L,curY,16):
      print("Error solveLU_lower.2 with %d and %d"%(curY, b))
  # new test---LU Decomposition, lower
  L = [[1,0,0,0,0],
       [1,3,1,0,0],
       [1,3,1,0,0],
       [7,3,1,1,1],
       [5,3,7,1,1]]
  y = [1,1,5,5,11]
  b = applyMatVecPlain(L,y,16) 
  yDash = solveLU_lower(L,b, 16)
  for curY in yDash:
    if b != applyMatVecPlain(L,curY,16):
      assert isVec(curY,16)
      print("Error solveLU_lower.3 with %d and %d"%(curY, b))

  # new test---LU Decomposition, upper
  U = [[3,1, 3, 5, 7],
       [1,3, 1, 3,11],
       [0,0,13,11, 7],
       [0,0, 5, 7,13],
       [0,0, 0, 0, 9]]
  x = [1,13,5,11,7]
  y = applyMatVecPlain(U,x,16) 
  xDash = solveLU_upper(U,y,16)
  for curX in xDash:
    assert isVec(curX,16)
    if y != applyMatVecPlain(U,curX,16):
      print("Error solveLU_upper.1 with "+str(curX)+" and "+str(y))
  # new test - upper triangular
  U = [[7,1,13, 5, 7],
       [1,3,11, 3,11],
       [0,0,13,11, 7],
       [0,0, 5, 5,13],
       [0,0, 0, 0, 9]]
  x = [1,3,5,15,7]
  y = applyMatVecPlain(U,x,16) 
  xDash = solveLU_upper(U,y,16)
  for curX in xDash:
    assert isVec(curX,16)
    if y != applyMatVecPlain(U,curX,16):
      print("Error solveLU_upper.2 with "+str(curX)+" and "+str(y))
  # new test - upper triangular
  U = [[7,1,13, 1, 7],
       [1,3,11, 3, 1],
       [0,0,13, 5, 5],
       [0,0, 5, 5,13],
       [0,0, 0, 0, 9]]
  x = [1,5,7,3,7]
  y = applyMatVecPlain(U,x,16) 
  xDash = solveLU_upper(U,y,16)
  for curX in xDash:
    assert isVec(curX,16)
    if y != applyMatVecPlain(U,curX,16):
      print("Error solveLU_upper.3 with "+str(curX)+" and "+str(y))

  # new test LU-solving
  L = [[1,0,0,0,0],
       [1,3,1,0,0],
       [1,3,1,0,0],
       [7,3,1,1,1],
       [5,3,7,1,1]]
  U = [[7,1,13, 1, 7],
       [1,3,11, 3, 1],
       [0,0,13, 5, 5],
       [0,0, 5, 5,13],
       [0,0, 0, 0, 9]]
  x = [1,1,5,5,11]
  y = applyMatVecPlain(U,x,16)   
  b = applyMatVecPlain(L,y,16) 
  xDash = solveLU(L,U,b,16)
  for curX in xDash:
    assert isVec(curX,16)
    # apply both matrices
    curY = applyMatVecPlain(U,curX,16)
    curB = applyMatVecPlain(L,curY,16)
    if curB != b:
      print("Error solveLU.1 with "+str(curX)+", "+str(curY) + " and " + str(curB))
  # new test LU-solving
  L = [[1,0,0,0,0],
       [1,3,1,0,0],
       [1,3,1,0,0],
       [7,3,1,1,1],
       [5,3,7,1,1]]
  U = [[7,1,13, 1, 7],
       [1,3,11, 3, 1],
       [0,0,13, 5, 5],
       [0,0, 5, 5,11],
       [0,0, 0, 0, 9]]
  x = [1,7,5,1,11]
  y = applyMatVecPlain(U,x,16)   
  b = applyMatVecPlain(L,y,16) 
  xDash = solveLU(L,U,b,16)
  for curX in xDash:
    assert isVec(curX,16)
    # apply both matrices
    curY = applyMatVecPlain(U,curX,16)
    curB = applyMatVecPlain(L,curY,16)
    if curB != b:
      print("Error solveLU.2 with "+str(curX)+", "+str(curY) + " and " + str(curB))
  # new test LU-solving
  L = [[1,0,0,0,0],
       [1,3,1,0,0],
       [1,3,1,0,0],
       [7,3,1,1,1],
       [5,3,7,1,1]]
  U = [[7,1,13,11, 7],
       [1,3,11, 3, 1],
       [0,0,13,15, 5],
       [0,0, 5, 5,13],
       [0,0, 0, 0, 9]]
  x = [1,3,5,7,13]
  y = applyMatVecPlain(U,x,16)   
  b = applyMatVecPlain(L,y,16) 
  xDash = solveLU(L,U,b,16)
  for curX in xDash:
    assert isVec(curX,16)
    # apply both matrices
    curY = applyMatVecPlain(U,curX,16)
    curB = applyMatVecPlain(L,curY,16)
    if curB != b:
      print("Error solveLU.3 with "+str(curX)+", "+str(curY) + " and " + str(curB))
      
  # test random generation
  for i in range(10):
    assert isLU_lower(rndLU_lower(7,512),512), "Wrong format LU lower"
    assert isLU_upper(rndLU_upper(7,512),512), "Wrong format LU upper"     
  
  # polynomials
  # check polynomials
  if not(isPoly({0:1},16)): print("Error isPoly.1")
  if not(isPoly({0:1, 1:5},16)): print("Error isPoly.2")
  if isPoly({0:1, 1:6},16): print("Error isPoly.3")
  
  # check polynomial multiplicaton
  R = mulPoly({0:1}, {0:7}, 16)
  assert R == {0:7}, "Wrong mulPoly.1 with "+str(R)
  R = mulPoly({0:1, 1:3}, {0:7, 1:5}, 16)
  assert R == {0:7, 1:10, 2:15}, "Wrong mulPoly.2 with "+str(R)
  R = mulPoly({0:1, 1:3, 2:7}, {0:5, 1:7, 2:3, 3:11}, 16)
  assert R == {0: 5, 1: 6, 2: 11, 3: 5, 4: 6, 5: 13}, "Wrong mulPoly.3 with "+str(R)
  R = mulPoly({0:1, 1:3, 2:7}, {0:5, 1:7, 2:3, 3:11}, 64)
  assert R == {0: 5, 1: 22, 2: 59, 3: 5, 4: 54, 5: 13}, "Wrong mulPoly.3 with "+str(R)
  
  # find polynomials B for A.B is an odd polynomial  
  res = mulPolyFindBCoeffs({0:1, 1:3, 2:5}, 3, 64)
  assert res ==  {1: [[0, 1], [1, 0]], 4: [[1, 3], [2, 2]]}, "Wrong coeffs mulPolyFindBCoeffs.1 with "+str(res)
  res = mulPolyFindBCoeffs({0:1, 1:3, 2:5, 3:7}, 5, 64)
  assert res == {1: [[0, 1], [1, 0]], 3: [[0, 3], [1, 2], [2, 1], [3, 0]], 4: [[0, 4], [1, 3], [2, 2], [3, 1]], 5: [[0, 5], 
                    [1, 4], [2, 3], [3, 2]], 7: [[2, 5], [3, 4]]}, "Wrong coeffs mulPolyFindBCoeffs.2 with "+str(res) 

  ##################################
  # sym - symbolic
  assert symIsPoly("1*a1*b1*",set(["a1","b1"]),16)
  assert symIsPoly("1*a1*b1*+5*",set(["a1","b1"]),16)
  assert not(symIsPoly("1*a1*b1*+5*c1*",set(["a1","b1"]),16))
  assert symIsPoly("1*a1*b1*+5*c1*",set(["a1","b1","c1"]),16)
  assert not(symIsPoly("1*a1*b1*+c1*",set(["a1","b1","c1"]),16))
  assert symIsPoly("1*",set([]),16)
  assert symIsPoly("0*",set([]),16), "symIsPoly 0"
  
  assert symPolyIsOdd("1*a*",16), "symIsOutOdd.1"
  assert symPolyIsOdd("1*a*+1*b*",16) == False, "symIsOutOdd.2"
  assert symPolyIsOdd("1*a*+2*b*",16), "symIsOutOdd.3"
  
  assert symIsLinear("1*a*",["a","b"],16), "symIsLinear.1"
  assert symIsLinear("1*a*b*",["a","b"],16) == False, "symIsLinear.2"
  assert symIsLinear("1*a*+5*b*",["a","b"],16), "symIsLinear.3"
  assert symIsLinear("1*",["a","b"],16) == False, "symIsLinear.4"
  
  outSet = symAllVars("1*a*b*",16)
  assert outSet == set(["a","b"]), "symAllVars.1 wrong for "+str(outSet)
  outSet = symAllVars("1*a*b*+1*c*+5*d*",16)
  assert outSet == set(["a","b","c","d"]), "symAllVars.2 wrong for "+str(outSet)
  outSet = symAllVars("1*a5*b3*",16)
  assert outSet == set(["a5","b3"]), "symAllVars.1 wrong for "+str(outSet)
  
  outStr = str(symSetEqs(["1*a1*b1*+5*c1*"],set(["a1","b1","c1"]),{"a1":5},16))
  assert outStr == "['5*b1*+5*c1*']", "symSeqEqs.1: Different output " + outStr
  outStr = str(symSetEqs(["1*a1*b1*+5*c1*","1*a1*"],set(["a1","b1","c1"]),{"a1":5},16))
  assert outStr == "['5*b1*+5*c1*', '5*']", "symSeqEqs.2: Different output " + outStr
 
  outStr = str(symPolyMult("a", 2, "s", 3, 16))
  assert outStr == "['1*a0*s0*', '1*a0*s1*+1*a1*s0*', '1*a0*s2*+1*a1*s1*', '1*a1*s2*']", "symPolyMult.1 - wrong output: " + outStr
  outStr = str(symPolyMult("a", 4, "s", 5, 16))
  assert  outStr == "['1*a0*s0*', '1*a0*s1*+1*a1*s0*', '1*a0*s2*+1*a1*s1*+1*a2*s0*', '1*a0*s3*+1*a1*s2*+1*a2*s1*+1*a3*s0*', '1*a0*s4*+1*a1*s3*+1*a2*s2*+1*a3*s1*', '1*a1*s4*+1*a2*s3*+1*a3*s2*', '1*a2*s4*+1*a3*s3*', '1*a3*s4*']", "symPolyMult.2 - wrong output: " + outStr
  outStr = str(symPolyMult("a", 3, "s", 2, 16))
  assert outStr == "['1*a0*s0*', '1*a0*s1*+1*a1*s0*', '1*a1*s1*+1*a2*s0*', '1*a2*s1*']", "symPolyMult.3 - wrong output: " + outStr
  
  outStr = symMultFacPoly(1, "1*a*+3*b*+5*", set(["a","b"]), 16)
  assert outStr == "1*a*+3*b*+5*", "symMultFacPoly.1: "+outStr
  outStr = symMultFacPoly(3, "1*a*+3*b*+5*", set(["a","b"]), 16)
  assert outStr == "3*a*+9*b*+15*", "symMultFacPoly.2: "+outStr
  
  assert symSubtractTerm("1*a0*s1*+1*a1*s0*", "1*a0*s1*", 16) == "1*a1*s0*"
  assert symSubtractTerm("1*a0*s1*+1*a1*s0*", "2*a0*s1*", 16) == "15*a0*s1*+1*a1*s0*"
  assert symSubtractTerm("1*a0*s1*+1*a1*s0*", "2*a0*s2*", 16) == "1*a0*s1*+1*a1*s0*+14*a0*s2*"
  assert symSubtractTerm("", "1*a0*s2*", 16) == "15*a0*s2*"
  
  outStr = symSortTerms("1*b*a*",["a","b"],16)
  assert outStr == "1*a*b*", "symSortTerms.1: "+outStr
  outStr = symSortTerms("1*b*a*+3*a*b*",["a","b"],16)
  assert outStr == "1*a*b*+3*a*b*", "symSortTerms.2: "+outStr
  outStr = symSortTerms("1*b*a1*+3*a2*b*",["a1","a2","b"],16)
  assert outStr == "1*a1*b*+3*a2*b*", "symSortTerms.3: "+outStr
  outStr = symSortTerms("1*b*3*a*",["a","b"],16)
  assert outStr == "3*a*b*", "symSortTerms.4: "+outStr
  outStr = symSortTerms("1*3*b1*c1*",["b1","c1"],16)
  assert outStr == "3*b1*c1*", "symSortTerms.5: "+outStr
  outStr = symSortTerms("1*b*3*c*+a*b*3*5*+a*7*",["a","b","c"],16)
  assert outStr == "3*b*c*+15*a*b*+7*a*", "symSortTerms.6: "+outStr
  
  res = symMulPolyPoly("1*a_1*+1*b_1*i*", "1*a_2*+1*b_2*i*", 256) 
  assert res == "1*a_1*a_2*+1*a_1*b_2*i*+1*a_2*b_1*i*+1*b_1*b_2*i*i*", "symMulPolyPoly.1: "+res
  
  outEq = symAddUp("1*a*b*+3*a*b*+5*a*b*",16)
  assert outEq == "9*a*b*", "symAddUp.1 wrong with " + outEq
  outEq = symAddUp("1*a*b*+3*a*c*+5*a*d*",16)
  assert outEq == "1*a*b*+3*a*c*+5*a*d*", "symAddUp.2 wrong with " + outEq
  
  outStr = str(symSetEqsPoly(["1*a1*b1*+5*c1*"],set(["a1","b1","c1"]),{"a1":"1*b1*+3*c1*"},16))
  assert outStr == "['1*b1*b1*+3*b1*c1*+5*c1*']", "symSetEqsPoly.1 with "+outStr
  outStr = str(symSetEqsPoly(["1*a1*b1*"],set(["a1","b1","c1"]),{"a1":"5*b1*+3*c1*"},16))
  assert outStr == "['5*b1*b1*+3*b1*c1*']", "symSetEqsPoly.2 with "+outStr
  outStr = str(symSetEqsPoly(["1*a*b*+3*a*c*+1*b*c*"],set(["a","b","c"]),{"a":"1*b*+1*c*"},16))
  assert outStr == "['1*b*b*+5*b*c*+3*c*c*']", "symSetEqsPoly.3 with "+outStr
  outStr = str(symSetEqsPoly(["7*a*b*+9*a*b*"],set(["a","b","c"]),{"a":"1*b*"},16))
  assert outStr == "[]", "symSetEqsPoly.4 with "+outStr
  
  sSet = {"s0":1, "s1":3, "s2":1}
  outTup = str(symRewriteEqsLin("a", 3, "s", 3, sSet, 16))
  assert outTup == "(['1*a2*', '9*a2*', '1*a2*'], {'a1': '13*a2*', 'a0': '1*a2*'})", "symRewriteEqsLin.1: "+outTup
  sSet = {"s0":1, "s1":3}
  outTup = str(symRewriteEqsLin("a", 3, "s", 2, sSet, 16))
  assert outTup == "(['9*a2*', '3*a2*'], {'a1': '5*a2*', 'a0': '9*a2*'})", "symRewriteEqsLin.2: "+outTup
  sSet = {"s0":1, "s1":3}
  outTup = str(symRewriteEqsLin("a", 2, "s", 2, sSet, 16))
  assert outTup == "(['5*a1*', '3*a1*'], {'a0': '5*a1*'})", "symRewriteEqsLin.3: "+outTup
  sSet = {"s0":1, "s1":3, "s2":3, "s3":3, "s4":1, "s5":3, "s6":1, "s7":3}
  outTup = str(symRewriteEqsLin("a", 4, "s", 8, sSet, 16))
  assert outTup == "(['5*a1*+2*a3*', '2*a1*+9*a3*', '3*a1*+6*a3*', '3*a3*'], {'a2': '5*a3*', 'a0': '5*a1*', 'a1': '8*a3*+7*a1*', 'a3': '1*a3*'})", "symReweriteEqsLine.4: "+outTup
  sSet = {"s0":1, "s1":3}
  outTup = str(symRewriteEqsLin("a", 3, "s", 2, sSet, 512))
  assert outTup == "(['57*a2*', '3*a2*'], {'a1': '341*a2*', 'a0': '57*a2*'})", "symRewriteEqsLin.4"
  
  #symSolveAxb([[1]],[3],16)
  
  #symSolveAxb([[1,3,5],[1,1,1],[3,3,3]],[9,3,9],16)
  
  #symSolveAxb([[1,3,5],[1,1,1],[3,3,3]],[1,3,5],16)
  
  # done
  print("Done Testing")
  return


def symSolveAxb(A,b,D):
  n = len(b)
  assert n >= 1, "Too small n with "+str(n)
  assert (n % 2) == 1, "Even n with "+str(n)
  for i in range(n):
    assert len(A[i]), "Wrong dimension for A at {} with {}".format(n,A[i])
  for i in range(n):
    assert isElem(b[i],D), "Non-element for "+str(b[i])
  for i in range(n):
    for j in range(n):
      assert isElem(A[i][j],D), "Non-element for "+str(A[i][j])   
      
  allVars = set(["x"+str(i) for i in range(n) ])  
  eqs = []; repDict = {}
  for i in range(n):
    curStr = "+".join([str(A[i][j])+"*x"+str(j)+"*" for j in range(n)] + [ str(D-b[i])+"*" ])
    eqs.append(curStr)
    print("Got "+curStr)

  # simplify the system, eliminate closed equations
  done = False
  while (not done):
    done = True
    # check if some polynomial has only one variable - this means the variable is zero
    # check if we have closed equations
    while len(eqs) != 0:
      # find a closed equation with minimal number of terms  
      i = -1; foundEq = -1; foundTerms = 10**100; foundLen = 10**100
      while True:
        i += 1    
        if i >= len(eqs): break
        if symPolyIsOdd(eqs[i],D): continue # active equation
        print("even with {}".format(eqs[i]))
        
        eqLen = len(eqs[i])
        terms = eqs[i].count("+")
        if (terms < foundTerms) or ((terms == foundTerms) and (eqLen < foundLen)): 
          foundTerms = terms; foundEq = i; foundLen = eqLen  
          print("found {} and {}".format(foundEq,foundLen))
      print("might found some {}".format(foundEq))  
      if foundEq == -1: break  # no closed equation      
      print("found some {}".format(foundEq))
      # remove one variable, make sure leading term is 1
      if eqs[foundEq].count("+") >= 1: t,r = eqs[foundEq].split("+",1)
      else: t = eqs[foundEq]; r = ""
      
      f,v = t.split("*",1)
      assert f.isdigit(), "Wrong number with "+f
      
      f = int(f); 
      if (f % 2) == 1:
        f = (D -f) % D; f = invMul(f, D)
      #else:
      #  # we have an even factor here---split into two odd factors
      #  r += ("" if r=="" else "+") + (str((f-1) % D))+"*"+v
      #  f = 1
      repVar = v.replace("*","")
      print("f: "+str(f))
      if r != "": r = symMultFacPoly(f, r, allVars, D)
      repDict[repVar] = r
      # remove var/Eqs
      del eqs[foundEq]
      # set the variable accordingly
      print("rep "+str({repVar: repDict[repVar]}))
      eqs = symSetEqsPoly(eqs,allVars,{repVar: repDict[repVar]},D)
              
      done = False
    print("outRep "+str(repDict))  
    return eqs,repDict
    
         
testAll()
#printSym()

